### ISSUE TITLE
Gateway Time-out 

### ISSUE THREAD

**Issue by dlogan** [CellProfiler/BatchProfiler#21]
BatchProfiler is returning a Gateway Time-out for [Batch 145](http://imagewebrhel6/batchprofiler/cgi-bin/ViewBatch.py?batch_id=145)

```
Gateway Time-out

The gateway did not receive a timely response from the upstream server or application.

Apache/2.2.15 (Red Hat) Server at imagewebrhel6 Port 80
```

Initially it did give its normal output list of jobs, but subsequent refreshes just time out.

**Comment by dlogan** [comment]
I tried older batches, and they all time out.  

`qstat -u imageweb
`shows 180 jobs running, which is the right amount, so hopefully this is just a display query issue(?)

**Comment by LeeKamentsky** [comment]
likely the webserver is hosed.

**Comment by LeeKamentsky** [comment]
Database needs a reset. Not batchprofiler's fault.

**Comment by dlogan** [comment]
Database is back online, but after I resubmitted Batch 145 via BatchProfiler, I now get the same Gateway Timeout

**Comment by LeeKamentsky** [comment]
Can you hold off on resubmitting? Something is locking the database and I can't get any database access while it's locked.

**Comment by dlogan** [comment]
Yes, I will hold off resubmitting. Feel free to kill the jobs for Batch 145
if they are running now.

## David

Sent from my phone.
Please excuse terse tappings.
