### ISSUE TITLE
Job shows as complete even though failed

### ISSUE THREAD

**Issue by braymp** [CellProfiler/BatchProfiler#6]
A job failed due to a directory access error (see attached .txt log) yet the webpage showed "Complete". The corresponding .err log was empty.
[error.txt](https://github.com/CellProfiler/BatchProfiler/files/5053/error.txt)

**Comment by LeeKamentsky** [comment]
I'm pretty sure this is a bug in CellProfiler. I just tried running CellProfiler on Pirita using a project that points to a missing file, [Batch_data.h5](http://broadinstitute.org/~leek/bpissue6/Batch_data.h5), and then I ran it headless from the command line. It prints an error stack trace, but the exit code (`echo $?`) is 0. See https://github.com/CellProfiler/CellProfiler/issues/1603.
